version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["02:f1:82:94:c2:69:4d:65:9f:4d:80:59:71:37:60:59"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
      - run:
          name: Configure server
          commandd: |
            ansible-playbook -i inventory.txt main-remote.yml
workflows:
  my_workflow:
    jobs:
      - configure_infrastructure